### PR TITLE
Instruction on running on a mac

### PR DESCRIPTION
**Pull request by danslee**
Basic instructions on how to run the app on a mac.

### CODE REVIEW

**Comment by danslee** [comment]
Hey, after a fair bit of trial and error, I figured out how to run this from a mac. Thanks for making this repo!

**Comment by thaohoangc3** [comment]
Thanks @danslee for making this pr. This comes in really handy 'cuz I don't have access to any Windows machine.

**Comment by danslee** [comment]
You’re very welcome @thaohoangc3! I’m glad it was helpful!

**Comment by sh1r4s3** [comment]
@danslee, @thaohoangc3 JFYI some time ago I've made a small utility to reprogram IFD-68 keyboards by reversing the USB protocol they are using. I've tested it on Linux based systems but I believe it should work on Mac and BSD systems as well because it is using libusb which should be available on Mac e.g. through brew.
https://github.com/sh1r4s3/ifd-68
The utility doesn't allow to program macro combos, only basic remapping is available. I can try to add that functionality later (also PRs are very welcome) if there will be interested in it. For me the basic remapping is the only thing I need so I didn't invest more time on it.

CC: @GonzaloAlvarez

**Pull request merged**
